[connections.tidb]
dialect = "mysql"
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
port = 4000
database = "contract_management"
username = "2togiDCHrG3RFGf.root"
password = "1nWRCnwmEh6mV0XL"
ssl_ca = "isrgrootx1.pem"
